import _ from 'lodash'

const types = [
  'AUTH_UPDATE',

  'BOARD_UPDATE',

  'COMMENT_CREATE',
  'COMMENT_DELETE',
  'COMMENT_UPDATE',

  'CURRENT_USER_RECEIVE',
  'CURRENT_USER_UPDATE',

  'LIST_ARCHIEVE',
  'LIST_CREATE',
  'LIST_MOVE',
  'LIST_UPDATE',

  'PAGE_BOARD_RECEIVE',
  'PAGE_CHANGE',
  'PAGE_PROJECTS_RECEIVE',
  'PAGE_PROJECT_RECEIVE',
  'PAGE_TASK_RECEIVE',

  'PROJECT_UPDATE',

  'SEARCH_RECEIVE',

  'TASKS_FILTER_BY_USER',
  'TASKS_FILTER_BY_LABEL',
  'TASK_ARCHIEVE',
  'TASK_CREATE',
  'TASK_MOVE',
  'TASK_RECEIVE',
  'TASK_RESET',
  'TASK_UPDATE',

  'USER_UPDATE',
]

export default _.keyBy(types, type => type)
